"""add premium fields

Revision ID: 1c9a896fcc3c
Revises: fc4ad283cfb7
Create Date: 2026-03-31 15:51:42.550993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9a896fcc3c'
down_revision: Union[str, None] = 'fc4ad283cfb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('analysis_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('quota_reset_at')
        batch_op.drop_column('analysis_count')
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
