"""Add domain to role_profiles

Revision ID: cb6c6dec804d
Revises: 761c24af95c0
Create Date: 2026-03-28 20:56:55.264787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6c6dec804d'
down_revision: Union[str, None] = '761c24af95c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    with op.batch_alter_table('role_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=100), nullable=False, server_default='Software Engineering'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_profiles', schema=None) as batch_op:
        batch_op.drop_column('domain')

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('target_domain')

    # ### end Alembic commands ###
