"""
Predefined skills dictionary for CV skill extraction.
Organized by category for structured matching and reporting.
"""

SKILLS_DATA: list[dict[str, str]] = [
    # ---- Programming Languages ----
    {"name": "Python", "category": "programming"},
    {"name": "JavaScript", "category": "programming"},
    {"name": "TypeScript", "category": "programming"},
    {"name": "Java", "category": "programming"},
    {"name": "C#", "category": "programming"},
    {"name": "C++", "category": "programming"},
    {"name": "C", "category": "programming"},
    {"name": "Go", "category": "programming"},
    {"name": "Rust", "category": "programming"},
    {"name": "PHP", "category": "programming"},
    {"name": "Ruby", "category": "programming"},
    {"name": "Swift", "category": "programming"},
    {"name": "Kotlin", "category": "programming"},
    {"name": "Scala", "category": "programming"},
    {"name": "R", "category": "programming"},
    {"name": "MATLAB", "category": "programming"},
    {"name": "SQL", "category": "programming"},
    {"name": "Dart", "category": "programming"},
    {"name": "Bash", "category": "programming"},
    {"name": "PowerShell", "category": "programming"},

    # ---- Web Frameworks ----
    {"name": "React", "category": "framework"},
    {"name": "Angular", "category": "framework"},
    {"name": "Vue.js", "category": "framework"},
    {"name": "Next.js", "category": "framework"},
    {"name": "Node.js", "category": "framework"},
    {"name": "Express.js", "category": "framework"},
    {"name": "Django", "category": "framework"},
    {"name": "Flask", "category": "framework"},
    {"name": "FastAPI", "category": "framework"},
    {"name": "Spring Boot", "category": "framework"},
    {"name": "ASP.NET", "category": "framework"},
    {"name": "Ruby on Rails", "category": "framework"},
    {"name": "Laravel", "category": "framework"},
    {"name": "Svelte", "category": "framework"},
    {"name": "jQuery", "category": "framework"},
    {"name": "Bootstrap", "category": "framework"},
    {"name": "Tailwind CSS", "category": "framework"},
    {"name": "Flutter", "category": "framework"},
    {"name": "React Native", "category": "framework"},

    # ---- Databases ----
    {"name": "PostgreSQL", "category": "database"},
    {"name": "MySQL", "category": "database"},
    {"name": "SQLite", "category": "database"},
    {"name": "MongoDB", "category": "database"},
    {"name": "Redis", "category": "database"},
    {"name": "Elasticsearch", "category": "database"},
    {"name": "Oracle", "category": "database"},
    {"name": "SQL Server", "category": "database"},
    {"name": "Firebase", "category": "database"},
    {"name": "DynamoDB", "category": "database"},
    {"name": "Cassandra", "category": "database"},
    {"name": "Neo4j", "category": "database"},

    # ---- DevOps & Cloud ----
    {"name": "Docker", "category": "devops"},
    {"name": "Kubernetes", "category": "devops"},
    {"name": "AWS", "category": "cloud"},
    {"name": "Azure", "category": "cloud"},
    {"name": "Google Cloud", "category": "cloud"},
    {"name": "CI/CD", "category": "devops"},
    {"name": "Jenkins", "category": "devops"},
    {"name": "GitHub Actions", "category": "devops"},
    {"name": "Terraform", "category": "devops"},
    {"name": "Ansible", "category": "devops"},
    {"name": "Nginx", "category": "devops"},
    {"name": "Linux", "category": "devops"},

    # ---- Tools & Platforms ----
    {"name": "Git", "category": "tool"},
    {"name": "GitHub", "category": "tool"},
    {"name": "GitLab", "category": "tool"},
    {"name": "Jira", "category": "tool"},
    {"name": "Confluence", "category": "tool"},
    {"name": "Figma", "category": "tool"},
    {"name": "VS Code", "category": "tool"},
    {"name": "IntelliJ", "category": "tool"},
    {"name": "Postman", "category": "tool"},
    {"name": "Swagger", "category": "tool"},
    {"name": "Slack", "category": "tool"},

    # ---- Data & AI/ML ----
    {"name": "Machine Learning", "category": "data_science"},
    {"name": "Deep Learning", "category": "data_science"},
    {"name": "TensorFlow", "category": "data_science"},
    {"name": "PyTorch", "category": "data_science"},
    {"name": "Scikit-learn", "category": "data_science"},
    {"name": "Pandas", "category": "data_science"},
    {"name": "NumPy", "category": "data_science"},
    {"name": "Matplotlib", "category": "data_science"},
    {"name": "Tableau", "category": "data_science"},
    {"name": "Power BI", "category": "data_science"},
    {"name": "Apache Spark", "category": "data_science"},
    {"name": "Hadoop", "category": "data_science"},
    {"name": "NLP", "category": "data_science"},
    {"name": "Computer Vision", "category": "data_science"},
    {"name": "Data Analysis", "category": "data_science"},
    {"name": "Data Visualization", "category": "data_science"},
    {"name": "Statistics", "category": "data_science"},

    # ---- Testing ----
    {"name": "Unit Testing", "category": "testing"},
    {"name": "Integration Testing", "category": "testing"},
    {"name": "Selenium", "category": "testing"},
    {"name": "Cypress", "category": "testing"},
    {"name": "Jest", "category": "testing"},
    {"name": "Pytest", "category": "testing"},
    {"name": "JUnit", "category": "testing"},
    {"name": "Test Automation", "category": "testing"},

    # ---- Soft Skills ----
    {"name": "Leadership", "category": "soft_skill"},
    {"name": "Teamwork", "category": "soft_skill"},
    {"name": "Communication", "category": "soft_skill"},
    {"name": "Problem Solving", "category": "soft_skill"},
    {"name": "Critical Thinking", "category": "soft_skill"},
    {"name": "Project Management", "category": "soft_skill"},
    {"name": "Agile", "category": "soft_skill"},
    {"name": "Scrum", "category": "soft_skill"},
    {"name": "Time Management", "category": "soft_skill"},
    {"name": "Presentation", "category": "soft_skill"},
    {"name": "Technical Writing", "category": "soft_skill"},
    {"name": "Mentoring", "category": "soft_skill"},

    # ---- Security ----
    {"name": "Cybersecurity", "category": "security"},
    {"name": "Penetration Testing", "category": "security"},
    {"name": "OAuth", "category": "security"},
    {"name": "JWT", "category": "security"},
    {"name": "Encryption", "category": "security"},

    # ---- Architecture & Design ----
    {"name": "REST API", "category": "architecture"},
    {"name": "GraphQL", "category": "architecture"},
    {"name": "Microservices", "category": "architecture"},
    {"name": "Design Patterns", "category": "architecture"},
    {"name": "System Design", "category": "architecture"},
    {"name": "OOP", "category": "architecture"},
    {"name": "Clean Architecture", "category": "architecture"},
    {"name": "Event-Driven Architecture", "category": "architecture"},

    # ---- Industrial Engineering / Supply Chain ----
    {"name": "ERP Systems", "category": "engineering"},
    {"name": "SAP", "category": "engineering"},
    {"name": "Excel", "category": "tool"},
    {"name": "Lean Manufacturing", "category": "engineering"},
    {"name": "Production Planning", "category": "engineering"},
    {"name": "Supply Chain Management", "category": "engineering"},
    {"name": "AutoCAD", "category": "tool"},
    {"name": "Lean Six Sigma", "category": "engineering"},
    {"name": "Process Optimization", "category": "engineering"},
    {"name": "Kaizen", "category": "engineering"},
    {"name": "Minitab", "category": "tool"},
    {"name": "Time Study", "category": "engineering"},
    {"name": "Value Stream Mapping", "category": "engineering"},
    {"name": "Inventory Optimization", "category": "engineering"},
    {"name": "Logistics", "category": "engineering"},
    {"name": "Purchasing", "category": "engineering"},
]
